//
//  colorCombi.swift
//  Personal Stylist
//
//  Created by Filip on 09/08/2019.
//  Copyright © 2019 Filip. All rights reserved.
//

import Foundation

let colorCombinations = [
    ["none", "darkGray", "darkGray", "white"],
    ["none", "lighrGray", "darkGray", "white"],
    ["none", "lighrGray", "darkGray", "black"],
    ["none", "lighrGray", "darkGray", "brown"],
    ["none", "lighrGray", "black", "white"],
    ["none", "lighrGray", "black", "black"],
    ["none", "darkRed", "darkGray", "white"],
    ["none", "darkRed", "darkGray", "black"],
    ["none", "lightRed", "darkGray", "black"],
    ["none", "red", "darkGray", "white"],
    ["none", "red", "darkGray", "black"],
    ["none", "babyBlue", "navy", "white"],
    ["none", "navy", "navy", "white"],
    ["none", "navy", "darkBlue", "white"],
    ["none", "navy", "navy", "brown"],
    ["none", "darkBlue", "navy", "white"],
    ["none", "darkBlue", "navy", "black"],
    ["none", "darkBlue", "navy", "brown"],
    ["none", "blue", "navy", "white"],
    ["none", "blue", "darkBlue", "white"],
    ["none", "blue", "navy", "black"],
    ["none", "blue", "navy", "brown"],
    ["none", "white", "darkGray", "white"],
    ["none", "white", "darkGray", "black"],
    ["none", "white", "darkGray", "brown"],
    ["none", "white", "babyBlue", "white"],
    ["none", "white", "babyBlue", "brown"],
    ["none", "white", "gray", "brown"],
    ["none", "white", "darkBlue", "brown"],
    ["none", "white", "navy", "white"],
    ["none", "white", "navy", "black"],
    ["none", "white", "navy", "brown"],
    ["none", "white", "black", "white"],
    ["none", "white", "black", "black"],
    ["none", "white", "black", "brown"],
    ["none", "black", "darkGray", "white"],
    ["none", "black", "darkGray", "black"],
    ["none", "black", "darkGray", "brown"],
    ["none", "black", "gray", "brown"],
    ["none", "black", "navy", "white"],
    ["none", "black", "navy", "black"],
    ["none", "black", "navy", "brown"],
    ["none", "black", "black", "white"],
    ["none", "black", "black", "black"],
    ["none", "black", "black", "brown"],
    ["none", "khaki", "darkgray", "white"],
    ["none", "khaki", "darkgray", "black"],
    ["none", "khaki", "black", "white"],
    ["none", "khaki", "black", "black"],
    ["none", "khaki", "navy", "wite"],
    ["none", "khaki", "navy", "black"],
    ["brown", "darkGray", "darkGray", "white"],
    ["brown", "lighrGray", "darkGray", "white"],
    ["brown", "lighrGray", "darkGray", "black"],
    ["brown", "lighrGray", "darkGray", "brown"],
    ["brown", "lighrGray", "black", "white"],
    ["brown", "lighrGray", "black", "black"],
    ["brown", "navy", "navy", "white"],
    ["brown", "navy", "navy", "brown"],
    ["brown", "darkBlue", "navy", "black"],
    ["brown", "darkBlue", "navy", "brown"],
    ["brown", "blue", "navy", "white"],
    ["brown", "blue", "navy", "black"],
    ["brown", "blue", "navy", "brown"],
    ["brown", "white", "darkGray", "white"],
    ["brown", "white", "darkGray", "brown"],
    ["brown", "white", "babyBlue", "white"],
    ["brown", "white", "babyBlue", "brown"],
    ["brown", "white", "navy", "white"],
    ["brown", "white", "navy", "brown"],
    ["brown", "white", "black", "white"],
    ["brown", "white", "black", "black"],
    ["brown", "white", "black", "brown"],
    ["brown", "black", "darkGray", "black"],
    ["brown", "black", "darkGray", "brown"],
    ["brown", "black", "navy", "brown"],
    ["brown", "black", "black", "white"],
    ["brown", "black", "black", "brown"],
    ["gray", "darkGray", "darkGray", "white"],
    ["gray", "white", "darkGray", "white"],
    ["gray", "white", "darkGray", "black"],
    ["gray", "white", "black", "white"],
    ["gray", "white", "black", "black"],
    ["gray", "black", "darkGray", "white"],
    ["gray", "black", "darkGray", "black"],
    ["gray", "black", "black", "white"],
    ["gray", "black", "black", "black"]
]
